# Admin.create!(name: 'Nathan Lewis', campus: 'Dragonstone MS', email: 'nathan_lewis@school.com', password_digest: "#{Admin.digest('drums123')}" )
# Admin.create!(name: 'John Smith', campus: 'Winterfell HS', email: 'john_smith@school.com', password_digest: "#{Admin.digest('trumpet123')}" )
# Admin.create!(name: 'Prithi Gupta', campus: 'Eyrie HS', email: 'prithi_gupta@school.com', password_digest: "#{Admin.digest('oboe123')}" )
Admin.create!(name: 'Nathan Lewis', campus: 'Dragonstone MS', email: 'nathan_lewis@school.com', password_digest: 'drums123' )
Admin.create!(name: 'John Smith', campus: 'Winterfell HS', email: 'john_smith@school.com', password_digest: 'trumpet123' )
Admin.create!(name: 'Prithi Gupta', campus: 'Eyrie HS', email: 'prithi_gupta@school.com', password_digest: 'oboe123' )

Teacher.create!(name: 'Jon Snow', email: 'lord_crow@school.com', admin_id: 1  )
Teacher.create!(name: 'Oberyn Martell', email: 'red_viper@school.com', admin_id: 1  )
Teacher.create!(name: 'Tyrion Lannister', email: 'the_imp@school.com', admin_id: 2  )
Teacher.create!(name: 'Petyr Baelish', email: 'littlefinger@school.com', admin_id: 2  )
Teacher.create!(name: 'Sandor Clegane', email: 'the_hound@school.com', admin_id: 3  )
Teacher.create!(name: 'Theon Greyjoy', email: 'reek@school.com', admin_id: 3  )

Student.create!(name: 'Robb Stark', grade: 9, email: 'robb@school.com', teacher_id: 1, admin_id: 1 )
Student.create!(name: 'Ramsay Bolton', grade: 10, email: 'ramsay@school.com', teacher_id: 2, admin_id: 1 )
Student.create!(name: 'Joffrey Baratheon', grade: 11, email: 'joffrey@school.com', teacher_id: 1, admin_id: 1 )
Student.create!(name: 'Bran Stark', grade: 12, email: 'bran@school.com', teacher_id: 3, admin_id: 2 )
Student.create!(name: 'Gregor Clegane', grade: 9, email: 'gregor@school.com', teacher_id: 4, admin_id: 2 )
Student.create!(name: 'Daenerys Targaryen', grade: 9, email: 'daenerys@school.com', teacher_id: 3, admin_id: 2 )
Student.create!(name: 'Arya Stark', grade: 8, email: 'arya@school.com', teacher_id: 5, admin_id: 3 )
Student.create!(name: 'Sansa Stark', grade: 7, email: 'sansa@school.com', teacher_id: 6, admin_id: 3 )
Student.create!(name: 'Khal Drogo', grade: 8, email: 'khal@school.com', teacher_id: 5, admin_id: 3 )
Student.create!(name: 'Jojen Reed', grade: 7, email: 'jojen@school.com', teacher_id: 6, admin_id: 3 )

Lesson.create(campus: 'Dragonstone MS', day: 'Monday', time: '10:00', teacher_id: 1, student_id: 1)
Lesson.create(campus: 'Dragonstone MS', day: 'Monday', time: '11:30', teacher_id: 2, student_id: 2)
Lesson.create(campus: 'Dragonstone MS', day: 'Monday', time: '3:00', teacher_id: 1, student_id: 3)
Lesson.create(campus: 'Winterfell HS', day: 'Tuesday', time: '3:30', teacher_id: 3, student_id: 4)
Lesson.create(campus: 'Winterfell HS', day: 'Tuesday', time: '9:30', teacher_id: 4, student_id: 5)
Lesson.create(campus: 'Winterfell HS', day: 'Wednesday', time: '11:00', teacher_id: 3, student_id: 6)
Lesson.create(campus: 'Winterfell HS', day: 'Thursday', time: '6:30', teacher_id: 3, student_id: 4)
Lesson.create(campus: 'Winterfell HS', day: 'Friday', time: '4:00', teacher_id: 4, student_id: 5)
Lesson.create(campus: 'Eyrie HS', day: 'Wednesday', time: '12:00', teacher_id: 5, student_id: 7)
Lesson.create(campus: 'Eyrie HS', day: 'Thursday', time: '12:30', teacher_id: 6, student_id: 8)
Lesson.create(campus: 'Eyrie HS', day: 'Friday', time: '1:00', teacher_id: 6, student_id: 8)
Lesson.create(campus: 'Eyrie HS', day: 'Thursday', time: '1:30', teacher_id: 5, student_id: 9)
Lesson.create(campus: 'Eyrie HS', day: 'Friday', time: '2:00', teacher_id: 6, student_id: 10)